services:
  postgres:
    image: 'postgres:latest'
    container_name: 'translator-container'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: translator
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: